name: EAS Build App

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ENV
    env:
      EAS_OWNER: ${{ secrets.EAS_OWNER }}
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🚀 Build app
        run: eas build --platform android --non-interactive